apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-metrics-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-metrics-app
  template:
    metadata:
      labels:
        app: python-metrics-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
