apiVersion: v1
kind: Service
metadata:
  name: python-metrics-app
  labels:
    app: python-metrics-app
spec:
  selector:
    app: python-metrics-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
